site_name: Furry 照明弹
repo_url: https://github.com/FurryUniverse/illumination
edit_uri: 'blob/master/docs/'
copyright: Copyright &copy; 2021 - 2022 Furry Universe
theme:
  name: material
  logo: assets/logo.png
  language: zh
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
plugins:
  - search:
      lang: ja
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - abbr
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
extra:
  version:
    provider: mike

copyright: 'Copyright &copy; 2021 - 2022 Furry Universe Team&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="tx-switch">
<br><a href="http://beian.miit.gov.cn">蜀ICP备18005894号-5</a>'
nav:
  - 关于项目:
    - 介绍: index.md
  - API:
    - 查询: api/search.md
    - 返回值参考表: api/respData.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FurryUniverse/illumination